using System;
using System.Collections.Generic;

namespace OAuthManagement.Models.LotusDb
{
    public partial class TblInventoryTransaction
    {
        public int InventoryTransactionId { get; set; }
        public int? OrderId { get; set; }
        public string DistributionChannelCode { get; set; }
        public string AuthorisationStatusId { get; set; }
        public int? BasketNextTransId { get; set; }
        public int? ReturnTransId { get; set; }
        public int? SaleTransId { get; set; }
        public int? TixPrintId { get; set; }
        public DateTime? TixLastPrintDateTime { get; set; }
        public string ChainName { get; set; }
        public int ChainNumber { get; set; }
        public string PromoterName { get; set; }
        public string PromoterRegionName { get; set; }
        public int? PromoterNumber { get; set; }
        public string SellerCode { get; set; }
        public string SellerId { get; set; }
        public int? PointNumber { get; set; }
        public bool? IsSeasonTransDependant { get; set; }
        public bool? IsMultiTransDependant { get; set; }
        public bool? IsSeasonTransLeader { get; set; }
        public bool? IsMultiTransLeader { get; set; }
        public bool? IsPaymentTrans { get; set; }
        public bool? IsPrePayTrans { get; set; }
        public bool? IsExchange { get; set; }
        public bool? IsMultiTrans { get; set; }
        public bool? IsBlockSell { get; set; }
        public bool? IsUndo { get; set; }
        public bool? IsRenewal { get; set; }
        public bool? TransFeeWaived { get; set; }
        public bool? HandlingFeeWaived { get; set; }
        public int? HowPaid { get; set; }
        public int? SurchargeBasis { get; set; }
        public int? ReturnOfSale { get; set; }
        public string ReturnReason { get; set; }
        public string EventName { get; set; }
        public string EventDateName { get; set; }
        public string SectionName { get; set; }
        public string RowSeatString { get; set; }
        public int? TicketCount { get; set; }
        public string TransactionType { get; set; }
        public int? SeatCategory { get; set; }
        public string ShowTag { get; set; }
        public int? TicketSequenceNum { get; set; }
        public int? TicketPaxNum { get; set; }
        public int? FirstTransGsn { get; set; }
        public decimal? AmountPaid { get; set; }
        public decimal? GrossAmountPaid { get; set; }
        public decimal? AmountOwed { get; set; }
        public decimal? SalesAmount { get; set; }
        public decimal? GrossSalesAmount { get; set; }
        public bool? IsDistributedMonies { get; set; }
        public bool? IsDistributedApplied { get; set; }
        public decimal? BfeeAmount { get; set; }
        public decimal? HandlingFeeAmount { get; set; }
        public decimal? TaxAmount { get; set; }
        public decimal? DistributedTaxAmount { get; set; }
        public decimal? DistributedTaxAmountApplied { get; set; }
        public int? Gstapplies { get; set; }
        public decimal? Gstrate { get; set; }
        public decimal? GstsiteLiable { get; set; }
        public bool? GstinclCamount { get; set; }
        public bool? GstinPriceAmount { get; set; }
        public bool? GstinBfeeAmount { get; set; }
        public bool? GstinHfeeAmount { get; set; }
        public decimal? TotalCommission { get; set; }
        public decimal? SalesIcamount { get; set; }
        public decimal? InsideChargeAmount { get; set; }
        public decimal? DistributedIcamount { get; set; }
        public decimal? DistributedIcamountApplied { get; set; }
        public decimal? CreditCardFeeAmountCalculated { get; set; }
        public decimal? PromoterCreditCardFee { get; set; }
        public decimal? PayTypeFeeAmount { get; set; }
        public string AfileName { get; set; }
        public int? OriginAccountNumber { get; set; }
        public bool? AllTicketsReturned { get; set; }
        public string BusinessType { get; set; }
        public int? Quantity { get; set; }
        public int? NonValueQty { get; set; }
        public int? CompQty { get; set; }
        public int? ZeroPriceQty { get; set; }
        public int? SubsQty { get; set; }
        public int? CompSubsQty { get; set; }
        public int? ZeroPriceSubsQty { get; set; }
        public int? NonValueSubsQty { get; set; }
        public int? AdmitCount { get; set; }
        public int? CompsAdmitCount { get; set; }
        public int? ZeroPriceAdmitCount { get; set; }
        public int? NonValueAdmitCount { get; set; }
        public bool? IsCollectable { get; set; }
        public decimal? CollectableAmountOwing { get; set; }
        public string DeliveryMethod { get; set; }
        public DateTime? TixLastPrintNoPrintTransDateTime { get; set; }
        public DateTime? TransactionDateTime { get; set; }
        public int? PaymentTransId { get; set; }
        public bool? GstinIcamount { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public byte[] Tstamp { get; set; }
        public string PlaceCode { get; set; }
        public string PromCode { get; set; }
        public int? CustomerId { get; set; }
        public bool? IsHoldOrRelease { get; set; }
        public string OriginalDeliveryMethod { get; set; }
        public decimal? DistributedAmount { get; set; }
        public decimal? ExchangeFee { get; set; }
        public decimal? ExchangeDiffCharged { get; set; }
        public decimal? ExchangeDiffWaived { get; set; }
        public string Allocations { get; set; }
        public bool? IsVoucherEvent { get; set; }
        public bool? PaxCardIssued { get; set; }

        public TblAuthorisationStatus AuthorisationStatus { get; set; }
        public TblOriginInventoryTransactionMap BasketNextTrans { get; set; }
        public TblCustomer Customer { get; set; }
        public TblDistributionChannel DistributionChannelCodeNavigation { get; set; }
        public TblOriginInventoryTransactionMap InventoryTransaction { get; set; }
        public TblOrder Order { get; set; }
        public TblOriginInventoryTransactionMap PaymentTrans { get; set; }
        public TblOriginInventoryTransactionMap ReturnTrans { get; set; }
        public TblOriginInventoryTransactionMap SaleTrans { get; set; }
    }
}
